from setuptools import setup, find_packages

setup(
    name="inpaint-anything",
    version="0.1.0",
    author="Tao Yu, Runseng Feng, Ruoyu Feng, Jinming Liu, Xin Jin, Wenjun Zeng, Zhibo Chen",
    description="Inpaint Anything: Segment Anything Meets Image Inpainting",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/llindqvi/Inpaint-Anything",
    packages=find_packages(),
    install_requires=[
        "pyyaml",
        "tqdm",
        "numpy",
        "easydict==1.9.0",
        "scikit-image",
        "scikit-learn",
        "opencv-python",
        "tensorflow",
        "joblib",
        "matplotlib",
        "pandas",
        "albumentations==0.5.2",
        "hydra-core==1.1.0",
        "pytorch-lightning==1.2.9",
        "tabulate",
        "kornia==0.8.1",
        "webdataset",
        "packaging",
        "wldhx.yadisk-direct",
        "timm",
        "torch",
        "torchvision",
        "Pillow",
        "gradio",
    ],
    python_requires=">=3.7",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    entry_points={
        "console_scripts": [
            "inpaint-remove=remove_anything:main",
            "inpaint-fill=fill_anything:main", 
            "inpaint-replace=replace_anything:main",
        ],
    },
    include_package_data=True,
)
